name : AutoFormat

on: [push]
jobs:
  autoformat_job:
    runs-on: ubuntu-latest
    name: Automatic formatting
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Autoformat
      id: format
      uses: SKIRT/auto-format@master
    - name: Autocommit
      if: steps.format.outputs.status == 'changed'
      run: |
        git config --global user.name 'OpFlow-Guardian'
        git config --global user.email 'guardian@opflow.git'
        git commit -am "[CI] Code auto formatted"
        git push
